### PR TITLE
Add firmware info from AVM FRITZ!Box 7490 version 113.06.50

### PR DESCRIPTION
**Pull request by mkresin**

### CODE REVIEW

**Comment by xdarklight** [comment]
Hi @mkresin,

could you please share your 7z version?
Mine is ```p7zip Version 9.38.1 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,8 CPUs,ASM)``` and with that I get:
```
$ 7z e filesystem.image filesystem_core.squashfs

7-Zip [64] 9.38 beta  Copyright (c) 1999-2014 Igor Pavlov  2015-01-03
p7zip Version 9.38.1 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,8 CPUs,ASM)

Processing archive: filesystem.image

Errors: 
Data Error
Warnings: 
There are data after the end of archive


No files to process


Archives with Errors: 1

Warnings: 1

Open Errors: 1
```

Running unsquashfs directly also doesn't seem to work:
```
$ unsquashfs4-lzma-avm-be filesystem.image 
Reading a different endian SQUASHFS filesystem on filesystem.image
Filesystem on filesystem.image is (0:0), which is a later filesystem version than I support!
```

**Comment by mkresin** [comment]
Yeah, should have mentioned it. I'm using the precompiled x86 linux binaries from http://sourceforge.net/projects/p7zip/files/p7zip/15.09/. The latest windows binaries do work as well.

Shall I add this information the extraction information as well (similar to the source of the unsquashfs4-lzma-avm-be)?

Some more insights about the (latest) AVM Images:

```FRITZ.Box_7490.113.06.50.image```: tar archive
```filesystem.image```: ext2 image with 256 byte fake squashfs header (WTF!)
```filesystem_core.squashfs```: [avm flavoured](http://freetz.org/browser/trunk/tools/make/squashfs4-host/AVM-BE-format.txt) squashfs 4 image

**Comment by xdarklight** [comment]
I've just tested it with a self-compiled version of p7zip 15.09: works fine!
I'll add that info, thanks!

**Comment by xdarklight** [comment]
Info added in a8894675c425e93f539b04b65406b43bbe6304c7

**Pull request merged**
